
services:
  app:
    build: .
    container_name: music-lib-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: music-lib-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always

volumes:
  postgres_data: